export const blogContentFr3: Record<string, string> = {
  'selena-gomez-kidney-transplant-awareness': `
    <p>C'est un sujet qui nous touche personnellement au YCOD, et voici pourquoi : lorsque <strong>Selena Gomez</strong> a révélé en septembre 2017 que sa meilleure amie <strong>Francia Raisa</strong> lui avait donné un rein pour lui sauver la vie, c'était la première fois que des millions de jeunes réfléchissaient sérieusement au don d'organes. Gomez souffre de lupus, une maladie auto-immune qui avait attaqué ses reins. Elle a partagé la nouvelle sur Instagram auprès de 130 millions d'abonnés, et du jour au lendemain, le don d'organes n'était plus un sujet hospitalier lointain — c'est devenu une conversation entre adolescents. Quand j'ai appris à quel point cette simple publication avait fait bouger les choses, j'ai compris : voilà ce que signifie vraiment percer le mur de l'indifférence.</p>

    <h3>Le pouvoir des célébrités</h3>
    <p>Donate Life America a signalé une hausse significative des inscriptions au registre de donneurs d'organes dans les semaines suivant l'annonce de Gomez. Les recherches Google pour « don d'organes » et « greffe de rein » ont explosé. L'histoire a touché des publics que les campagnes de santé publique traditionnelles atteignent rarement — les adolescents et jeunes adultes qui suivent la culture des célébrités mais n'avaient peut-être jamais rencontré d'informations sur le don d'organes. J'y pense constamment : 17 personnes meurent chaque jour en attente d'un organe, et parfois il faut la publication Instagram d'une pop star pour que les gens y prêtent attention. Ce n'est pas un échec des individus — c'est un échec du système à aller à leur rencontre.</p>

    <blockquote>« Il n'y a pas de mots pour décrire comment je pourrais remercier ma magnifique amie Francia Raisa. Elle m'a fait le cadeau ultime et le sacrifice suprême en me donnant son rein. Je suis incroyablement bénie. » — Selena Gomez, Instagram, septembre 2017</blockquote>

    <h3>Le sacrifice de Francia Raisa</h3>
    <p>Alors que l'attention se concentrait surtout sur Gomez, la décision de Francia Raisa de devenir donneuse vivante méritait une reconnaissance égale. Le don de rein de son vivant implique une chirurgie majeure, des semaines de convalescence et un suivi médical à vie. Raisa a ensuite parlé des défis physiques et émotionnels du processus, contribuant à déstigmatiser l'expérience et offrant des attentes réalistes aux donneurs vivants potentiels. Après qu'un membre de ma famille a eu besoin d'une greffe de rein, ce type de conversation honnête sur ce que traversent les donneurs est devenu profondément personnel pour moi. Le courage de Francia est exactement le genre d'histoire dont nous avons besoin davantage.</p>

    <h3>Impact sur les jeunes</h3>
    <p>Voici ce qui me revient sans cesse : l'histoire Gomez-Raisa a touché les jeunes — le public principal du YCOD — d'une manière qu'aucune campagne de sensibilisation n'aurait pu égaler. Pour de nombreux adolescents, c'était la première fois qu'ils réfléchissaient sérieusement au don d'organes. Cette histoire a démontré que l'insuffisance organique peut toucher n'importe qui, quels que soient l'âge, la célébrité ou la richesse. Elle a également mis en lumière le pouvoir profond du don de son vivant, où l'acte désintéressé d'une personne peut sauver la vie d'une autre. Les jeunes ne sont pas apolitiques — ce sont des agents du changement. Ils ont simplement besoin de quelque chose de réel pour allumer cette flamme. Cette histoire a été cette étincelle pour tant de gens.</p>

    <blockquote>« L'histoire de Selena a rendu le don d'organes concret pour toute une génération de jeunes qui n'y avaient jamais pensé auparavant. Ce type de sensibilisation n'a pas de prix. » — Donate Life America</blockquote>

    <h3>Entretenir la conversation</h3>
    <p>Les histoires de célébrités sont de puissants catalyseurs, mais voici ce que je dis toujours aux gens — la sensibilisation seule ne sauve pas de vies. C'est le système qui le fait. Nous, au YCOD, utilisons des histoires comme celle de Selena dans nos présentations scolaires et nos campagnes sur les réseaux sociaux pour toucher les jeunes. Mais nous ne nous arrêtons pas à la sensibilisation. Je pousse nos membres vers la question plus profonde : pourquoi l'Amérique utilise-t-elle encore un système de consentement explicite qui ne parvient pas à recueillir la volonté de millions de donneurs potentiels ? Selena Gomez a ouvert la porte. Je ne pouvais pas rester les bras croisés après avoir vu son impact — et vous non plus. Nous travaillons à faire adopter une législation de consentement présumé comme le <a href="/bill" target="_blank">projet de loi A07954</a>, car changer le choix par défaut sauve des vies.</p>
  `,

  'national-organ-waitlist-surpasses-100000': `
    <p>J'ai besoin que vous preniez un instant pour absorber ce chiffre : <strong>100 000 personnes</strong>. En 2023, c'est le nombre d'Américains inscrits sur la liste d'attente de greffe d'organes — et ce chiffre ne cesse d'augmenter malgré un nombre record de greffes réalisées chaque année. La liste d'attente, gérée par l'Organ Procurement and Transplantation Network, représente des personnes réelles dont la vie dépend de la réception d'un organe d'un donneur décédé ou vivant. Après qu'un membre de ma famille a eu besoin d'une greffe de rein, ces chiffres ont cessé d'être abstraits pour moi. Pour beaucoup sur cette liste, l'attente se terminera par la mort. Ce n'est pas qu'une crise — c'est un échec politique.</p>

    <h3>Qui figure sur la liste d'attente</h3>
    <p>La liste d'attente est composée en grande majorité de patients ayant besoin d'un rein — plus de 88 000 sur les 100 000+. Les patients en attente d'un foie constituent le deuxième groupe le plus important avec environ 10 000 personnes, suivis de ceux ayant besoin d'un cœur, de poumons, d'un pancréas et d'autres organes. Les données démographiques révèlent des inégalités flagrantes : les Américains noirs représentent 13 % de la population américaine mais environ 30 % de la liste d'attente pour un rein. Les Américains hispaniques sont également surreprésentés. Ce n'est pas seulement une crise sanitaire — c'est une question de justice.</p>

    <blockquote>« Derrière chaque numéro sur la liste d'attente se trouve une personne — un parent, un enfant, un ami — dont la vie est en jeu. 100 000, ce n'est pas juste une statistique. C'est une crise. » — Rapport de données de l'OPTN</blockquote>

    <h3>17 décès par jour</h3>
    <p>C'est le chiffre par lequel je commence chaque présentation du YCOD : environ 17 personnes meurent chaque jour aux États-Unis en attendant une greffe d'organe. Soit une personne toutes les 85 minutes. En 2022, plus de 6 000 personnes sont décédées sur la liste d'attente ou en ont été retirées parce qu'elles étaient devenues trop malades pour être greffées. Ces décès ne sont pas inévitables — ils sont le résultat d'un système qui ne parvient pas à recueillir suffisamment d'organes de donneurs pour répondre à la demande. C'est un problème politique, pas médical.</p>

    <h3>Pourquoi la liste ne cesse de s'allonger</h3>
    <p>La liste d'attente s'allonge pour plusieurs raisons. La population vieillit, et les maladies chroniques comme le diabète et l'hypertension — qui provoquent l'insuffisance rénale — deviennent plus répandues. De plus en plus de patients sont orientés vers la greffe à mesure que les résultats s'améliorent. Et si les taux de don ont augmenté, ils n'ont pas suivi le rythme de la demande. Le système de consentement explicite américain ne capte qu'une fraction des donneurs potentiels.</p>

    <blockquote>« Nous réalisons plus de greffes que jamais, et pourtant la liste ne cesse de s'allonger. Cela nous indique que des améliorations progressives ne suffisent pas — nous avons besoin d'un changement systémique. » — Société américaine de transplantation</blockquote>

    <h3>L'appel à l'action du YCOD</h3>
    <p>Voici ce que je dis à chaque législateur que nous rencontrons : la liste d'attente de plus de 100 000 personnes est l'argument le plus convaincant en faveur du consentement présumé au don d'organes en Amérique. Les pays ayant un système de consentement présumé ont systématiquement des taux de don plus élevés et des temps d'attente plus courts. L'Espagne, avec son modèle complet de consentement présumé, a pratiquement éliminé les décès sur liste d'attente pour les cœurs et les foies. Rien qu'à New York, plus de 8 000 personnes attendent. Je ne pouvais pas rester les bras croisés en sachant cela. Aucun Américain ne devrait mourir faute d'un organe que quelqu'un était prêt à donner mais n'a jamais pris le temps de s'inscrire. Changer le choix par défaut sauve des vies. Le <a href="/bill" target="_blank">projet de loi A07954</a> peut y parvenir — et nous, au YCOD, ne nous arrêterons pas tant qu'il ne sera pas adopté.</p>
  `,

  'donate-life-rose-parade-float': `
    <p>Voici quelque chose qui me touche à chaque fois : chaque jour de l'An, des millions d'Américains regardant le <strong>Défilé des Roses</strong> (Tournament of Roses Parade) à Pasadena, en Californie, voient un char pas comme les autres — le <strong>char Donate Life</strong>, un hommage floral époustouflant aux donneurs d'organes, de cornées et de tissus, ainsi qu'aux vies qu'ils ont sauvées. Depuis 2004, ce char est l'un des événements de sensibilisation au don d'organes les plus visibles et émotionnellement puissants du pays. Quand je l'ai vu pour la première fois, j'ai pensé : voilà à quoi devraient ressembler les 17 décès quotidiens dans l'imaginaire collectif — impossible à ignorer.</p>

    <h3>Un mémorial vivant</h3>
    <p>Ce qui rend le char Donate Life unique, c'est qu'il est décoré de <strong>floragraphes</strong> — des portraits floraux de donneurs d'organes décédés, créés par leurs familles. Chaque floragraphe est assemblé avec amour à partir de fleurs séchées, de graines et d'autres matériaux naturels par les proches du donneur. Le char transporte également des receveurs de greffe vivants, appelés « passagers », qui saluent la foule en tant que preuves vivantes du don de la vie. Après qu'un membre de ma famille a eu besoin d'une greffe de rein, je vois ces floragraphes différemment — chacun représente une famille qui a transformé son deuil en espoir.</p>

    <blockquote>« Décorer le floragraphe de mon fils a été l'une des expériences les plus réparatrices de ma vie. Savoir que son visage serait vu par des millions de personnes, que son histoire inspirerait quelqu'un à devenir donneur — cela donne un sens à sa mort. » — Parent d'un donneur d'organes décédé</blockquote>

    <h3>Le char de 2024</h3>
    <p>Le char Donate Life 2024, sur le thème « Le courage d'espérer », présentait 44 floragraphes de donneurs d'organes et transportait 24 receveurs vivants. Le char a remporté le « Trophée Extraordinaire » du défilé pour la démonstration la plus extraordinaire d'imagination et d'artisanat floral. La diffusion télévisée a atteint environ 40 millions de téléspectateurs, faisant de cet événement l'un des plus grands événements de sensibilisation au don d'organes de l'année.</p>

    <h3>Impact sur les inscriptions</h3>
    <p>Donate Life America constate systématiquement une hausse des inscriptions de donneurs autour du Défilé des Roses. L'organisation utilise le char comme pièce maîtresse d'une campagne de sensibilisation plus large pour le Nouvel An, encourageant les Américains à commencer l'année en s'inscrivant comme donneurs d'organes. Les réseaux sociaux amplifient le message, avec des photos de floragraphes et des témoignages de passagers partagés des millions de fois sur toutes les plateformes.</p>

    <blockquote>« Le char du Défilé des Roses touche des gens qui n'auraient peut-être jamais pensé au don d'organes autrement. Il transforme un moment de célébration en un moment de réflexion et d'action. » — Donate Life America</blockquote>

    <h3>Une source d'inspiration pour le YCOD</h3>
    <p>Le char Donate Life inspire directement ce que nous faisons au YCOD. Je partage les histoires du char avec nos membres et les utilise dans les présentations scolaires pour illustrer à la fois le deuil des familles de donneurs et la joie des receveurs de greffe. Ce n'est pas qu'un char de défilé — c'est un rappel que derrière chaque débat politique se trouvent de vraies histoires humaines. C'est ce qui me motive personnellement, et c'est ce qui nourrit notre plaidoyer en faveur d'une législation de consentement présumé à New York. Nous pouvons honorer ces donneurs en changeant le système, pas seulement les individus. Changer le choix par défaut sauve des vies — et cela commence avec le <a href="/bill" target="_blank">projet de loi A07954</a>.</p>
  `,

  'apple-health-app-organ-donor-registration': `
    <p>Quand j'ai appris qu'Apple avait ajouté l'inscription au registre des donneurs d'organes dans l'application <strong>Santé</strong> de l'iPhone en 2016, j'ai pensé : voilà ce que signifie penser en termes de système. En quelques clics, les utilisateurs peuvent s'inscrire comme donneurs d'organes. Cette fonctionnalité, développée en partenariat avec Donate Life America, est connectée directement au Registre national Donate Life. Depuis son lancement, elle est devenue l'un des outils les plus efficaces pour générer de nouvelles inscriptions de donneurs aux États-Unis. Et cela prouve ce que nous disons depuis toujours au YCOD — le problème n'est pas que les gens ne veulent pas donner. C'est que le système rend les choses trop difficiles.</p>

    <h3>Comment ça fonctionne</h3>
    <p>Lorsque les utilisateurs ouvrent l'application Santé sur leur iPhone, ils voient une section « Don d'organes » dans leur profil santé. En appuyant sur « S'inscrire avec Donate Life », ils sont guidés à travers un processus d'inscription simple qui demande des informations de base — nom, date de naissance, code postal — et les connecte au registre des donneurs de leur État. L'ensemble du processus prend moins de deux minutes. Les utilisateurs peuvent également modifier leur inscription ou se désinscrire à tout moment.</p>

    <blockquote>« Nous pensons qu'en facilitant l'inscription des gens comme donneurs d'organes, nous pouvons aider à sauver des vies. » — Tim Cook, PDG d'Apple</blockquote>

    <h3>Impact</h3>
    <p>Les résultats ont été remarquables. Donate Life America a rapporté que le premier jour suivant le lancement de la fonctionnalité, les inscriptions de donneurs d'organes ont bondi de 1 300 % via leurs systèmes. Des dizaines de millions d'utilisateurs d'iPhone ont depuis consulté la section don d'organes, et des millions ont complété leur inscription. La fonctionnalité s'est révélée particulièrement efficace pour atteindre les jeunes adultes — la tranche démographique la plus susceptible de posséder un iPhone et la moins susceptible de s'être déjà inscrite comme donneur.</p>

    <h3>Éliminer les frictions</h3>
    <p>Le succès de l'application Santé d'Apple illustre un principe dont je parle constamment au YCOD : <em>la friction tue</em>. La plupart des Américains soutiennent le don d'organes — les sondages montrent systématiquement un soutien supérieur à 90 % — mais bien moins s'inscrivent réellement. L'écart ne s'explique pas par l'opposition ; il s'explique par l'inconvénient. En plaçant l'inscription sur l'appareil que les gens portent partout, Apple a éliminé la friction. C'est exactement le même principe qui sous-tend la législation de consentement présumé : changer le choix par défaut sauve des vies. 17 personnes meurent chaque jour parce que le choix par défaut actuel est le mauvais.</p>

    <blockquote>« Quand vous supprimez les obstacles, les gens font ce qu'ils voulaient déjà faire. La plupart des gens veulent être donneurs d'organes — ils ont simplement besoin d'un moyen simple de dire oui. » — Donate Life America, commentant le partenariat avec Apple</blockquote>

    <h3>La technologie comme passerelle</h3>
    <p>Nous, au YCOD, voyons la technologie comme une passerelle puissante pendant que nous œuvrons en faveur du changement législatif. La fonctionnalité de l'application Santé d'Apple, les campagnes sur les réseaux sociaux et les outils d'inscription en ligne aident tous. Mais voici le problème — ils fonctionnent au sein d'un système de consentement explicite qui laisse encore passer des millions de donneurs potentiels. Je ne pouvais pas rester les bras croisés une fois que j'ai compris cela. La solution ultime combine la portée de la technologie avec le pouvoir de la législation : le consentement présumé comme choix par défaut, avec des outils numériques simples pour quiconque souhaite se désinscrire. C'est l'objet du <a href="/bill" target="_blank">projet de loi A07954</a> — réparer le système, pas simplement le rafistoler avec des applications.</p>
  `,

  'social-media-tiktok-organ-donation-awareness': `
    <p>Je serai honnête — quand j'ai lancé le YCOD, j'ai sous-estimé les réseaux sociaux. Mais <strong>TikTok</strong> en particulier est devenu l'une des forces les plus puissantes en matière de sensibilisation au don d'organes, et cela a changé ma façon de penser. Les receveurs de greffe partagent leur parcours, les familles de donneurs rendent hommage à leurs proches, et les professionnels de santé expliquent la science, touchant des audiences de millions de personnes. Pour la génération Z, les réseaux sociaux sont devenus la principale porte d'entrée pour découvrir et s'engager dans le don d'organes. Ce n'est pas qu'un divertissement — c'est là que des jeunes de 17 ans apprennent que 17 personnes meurent chaque jour en attente d'organes.</p>

    <h3>L'effet TikTok</h3>
    <p>Les vidéos taguées #organdonation sur TikTok ont cumulé des milliards de vues. Les receveurs de greffe partagent des vidéos avant-après montrant leurs transformations. Les donneurs vivants documentent leur chirurgie et leur convalescence. Les familles de donneurs publient des hommages à leurs proches. Le contenu est brut, personnel et authentique — exactement le type de récit qui résonne auprès des jeunes publics.</p>

    <blockquote>« J'ai publié un TikTok sur ma greffe de rein et il a obtenu 2 millions de vues en une nuit. Mes messages privés ont été inondés de personnes demandant comment devenir donneur d'organes. Les réseaux sociaux sont l'outil de sensibilisation le plus puissant que nous ayons. » — Receveur de greffe et créateur TikTok</blockquote>

    <h3>Pourquoi ça fonctionne</h3>
    <p>Les campagnes traditionnelles de don d'organes reposaient sur des brochures, des spots de sensibilisation et des actions de proximité dans les hôpitaux. Ces méthodes ont leur place, mais elles atteignent rarement les jeunes là où ils passent leur temps — sur leurs téléphones, en faisant défiler des vidéos courtes. Les réseaux sociaux démocratisent la sensibilisation : toute personne ayant une histoire et un smartphone peut toucher des millions de gens. La nature pair-à-pair des réseaux sociaux crée également une confiance que les messages institutionnels ne peuvent pas égaler. J'en ai fait l'expérience directe — nos publications YCOD obtiennent plus d'engagement avec un seul TikTok que des mois de sensibilisation traditionnelle.</p>

    <h3>Des campagnes devenues virales</h3>
    <p>Plusieurs campagnes de don d'organes ont connu un succès viral. Le défi #DonateLife encourageait les utilisateurs à partager pourquoi ils s'étaient inscrits comme donneurs. Les anniversaires de greffe — où les receveurs célèbrent l'anniversaire de leur transplantation — sont régulièrement en tendance. Les histoires d'inconnus donnant un rein à des personnes trouvées via les réseaux sociaux ont captivé les audiences et inspiré des actions concrètes.</p>

    <blockquote>« Quand un adolescent voit quelqu'un de son âge partager son histoire de greffe sur TikTok, l'impact est tout autre que celui d'un dépliant dans un cabinet médical. C'est réel, c'est accessible, et ça pousse les gens à agir. » — Stratège numérique de Donate Life</blockquote>

    <h3>La stratégie réseaux sociaux du YCOD</h3>
    <p>Nous, au YCOD, utilisons les réseaux sociaux comme un pilier central de notre plaidoyer — c'est là que vit notre public. J'encourage nos membres à partager des faits, des histoires personnelles et des appels à l'action sur Instagram, TikTok et d'autres plateformes. Ils créent du contenu qui parle directement à leurs pairs. Les jeunes ne sont pas apolitiques — ce sont des agents du changement, et les réseaux sociaux sont leur mégaphone. Nous avons constaté que c'est particulièrement efficace pour toucher les jeunes qui n'ont pas encore formé d'opinion sur le don d'organes — ce qui nous donne l'occasion de façonner ces points de vue tôt avec des informations précises et convaincantes et un appel clair à soutenir la législation de consentement présumé comme le <a href="/bill" target="_blank">projet de loi A07954</a>.</p>
  `,

  'seventeen-people-die-each-day-waiting': `
    <p>Voici la statistique qui a changé ma vie : toutes les 85 minutes, quelqu'un aux États-Unis meurt en attendant une greffe d'organe. Cela représente <strong>17 personnes chaque jour</strong> — plus de 6 000 par an — qui meurent non pas parce que la médecine les a abandonnés, mais parce que l'organe dont ils avaient besoin n'est jamais arrivé. Quand j'ai appris ce chiffre pour la première fois, je ne pouvais pas rester les bras croisés. Après qu'un membre de ma famille a eu besoin d'une greffe de rein, c'est devenu personnel. Ces décès ne sont pas inévitables. Ils sont la conséquence d'un choix politique, et ils peuvent être évités par un choix politique différent.</p>

    <h3>Les chiffres</h3>
    <p>Plus de 100 000 Américains figurent actuellement sur la liste d'attente de greffe d'organes. La grande majorité — plus de 88 000 — a besoin d'un rein. Le temps d'attente médian pour un rein provenant d'un donneur décédé est de 3 à 5 ans, selon la région géographique et le groupe sanguin. Pour certains patients, l'attente s'étend de 7 à 10 ans. Beaucoup ne survivent pas aussi longtemps. En plus des 17 personnes qui meurent chaque jour, beaucoup d'autres sont retirées de la liste parce qu'elles sont devenues trop malades pour être greffées.</p>

    <blockquote>« Ce ne sont pas des statistiques abstraites. Chacun de ces 17 décès quotidiens est une mère, un père, un enfant, un ami — quelqu'un dont la vie aurait pu être sauvée si un organe avait été disponible. » — Déclaration de position du YCOD</blockquote>

    <h3>Un échec politique, pas médical</h3>
    <p>C'est ce que je dis dans chaque présentation que je donne : c'est un problème politique, pas médical. La capacité médicale à greffer des organes est bien établie. Les États-Unis comptent parmi les meilleurs chirurgiens et hôpitaux de transplantation au monde. L'échec est structurel. Notre système de consentement explicite ne capte qu'une fraction des donneurs d'organes potentiels. Les sondages montrent que plus de 90 % des Américains soutiennent le don d'organes, mais seulement environ 58 % sont inscrits comme donneurs. Cet écart entre l'intention et l'action ? Il représente des milliers d'organes qui pourraient sauver des vies mais ne sont jamais disponibles. C'est le système, pas les individus, qui est le problème.</p>

    <h3>Ce que le consentement présumé changerait</h3>
    <p>Les pays dotés d'un système de consentement présumé ont joué un rôle majeur dans l'augmentation des taux de don à l'échelle mondiale. L'Espagne, pionnière du consentement présumé en 1979, mène le monde avec environ 49 donneurs décédés par million d'habitants. Si les taux de don post-mortem aux États-Unis se sont considérablement améliorés ces dernières années — atteignant environ 42 donneurs par million — plus de 100 000 personnes restent sur la liste d'attente. Les systèmes de consentement présumé, combinés à des réformes organisationnelles comme le réseau de coordinateurs de transplantation espagnol, se sont avérés efficaces pour combler l'écart entre le soutien du public au don et l'inscription effective des donneurs.</p>

    <blockquote>« Nous avons l'expertise médicale. Nous avons le soutien du public. Ce qui nous manque, c'est le cadre politique pour transformer les bonnes intentions en vies sauvées. La législation de consentement présumé est ce cadre. » — Note de plaidoyer du YCOD</blockquote>

    <h3>Notre obligation morale</h3>
    <p>Je crois que nous avons une obligation morale d'agir. Quand je sais — quand nous savons tous — qu'un changement de politique pourrait prévenir des milliers de décès évitables, l'inaction est un choix, et c'est le mauvais. Nous, au YCOD, appelons les législateurs de New York à adopter le <a href="/bill" target="_blank">projet de loi A07954</a> et les autres États à suivre. Les 17 personnes qui mourront aujourd'hui en attendant une greffe d'organe méritent mieux. Tout comme les 17 qui mourront demain. Changer le choix par défaut sauve des vies. Chaque jour où nous tardons à agir, nous choisissons le mauvais défaut.</p>
  `,

  'national-donate-life-month-april': `
    <p>Chaque mois d'avril, la nation observe le <strong>Mois national du don de vie</strong> (National Donate Life Month) — une campagne d'un mois coordonnée par Donate Life America pour sensibiliser au don d'organes, de cornées et de tissus. Pour nous au YCOD, avril est notre mois le plus important. C'est le moment où je mets toute mon énergie dans l'organisation d'événements, l'amplification de notre plaidoyer et le travail pour transformer la sensibilisation en action. Parce que voici le problème : 17 personnes meurent chaque jour en attente d'organes, et les mois de sensibilisation n'ont d'importance que s'ils conduisent à un changement systémique.</p>

    <h3>Historique du Mois du don de vie</h3>
    <p>Le Mois national du don de vie a été instauré en 2003 par Donate Life America, une alliance à but non lucratif regroupant des organismes de prélèvement d'organes, des centres de transplantation et d'autres parties prenantes. Cette observance est née de la Semaine nationale de sensibilisation au don d'organes et de tissus, proclamée pour la première fois par le président Reagan en 1983. Aujourd'hui, c'est l'un des mois de sensibilisation à la santé les plus reconnus du pays, avec des événements organisés dans les hôpitaux, les écoles, les centres communautaires et les capitales d'État à travers tout le pays.</p>

    <blockquote>« Le Mois national du don de vie ne se résume pas à la sensibilisation — il s'agit d'action. Chaque personne qui s'inscrit comme donneur d'organes en avril contribue à sauver une vie. » — Donate Life America</blockquote>

    <h3>Le bleu et le vert</h3>
    <p>Les couleurs bleu et vert de Donate Life deviennent visibles dans tout le pays en avril. Des monuments sont illuminés en bleu et vert. Les réseaux sociaux virent au bleu et vert avec des cadres de photos de profil et des publications de sensibilisation. Les écoles organisent des rassemblements, les hôpitaux accueillent des événements, et les communautés se réunissent pour honorer les donneurs et soutenir les receveurs. J'adore voir cette énergie — mais je rappelle toujours à nos membres du YCOD que ce n'est pas juste une question de couleurs et de campagnes. Il s'agit de changer le système, pas seulement de sensibiliser. La campagne visuelle est puissante, mais ce dont nous avons vraiment besoin, c'est d'un changement de politique.</p>

    <h3>La campagne d'avril du YCOD</h3>
    <p>Voici ce autour de quoi j'organise notre équipe chaque mois d'avril :</p>
    <p><strong>Présentations scolaires :</strong> Nos membres visitent des lycées et des universités à travers New York pour éduquer les étudiants sur le don d'organes et notre plaidoyer en faveur de la législation de consentement présumé.</p>
    <p><strong>Offensive sur les réseaux sociaux :</strong> Nous partageons quotidiennement des faits, des témoignages et des appels à l'action tout au long du mois d'avril, touchant des milliers de jeunes.</p>
    <p><strong>Journées de rédaction de lettres :</strong> Nous organisons des événements où les étudiants écrivent des lettres à leurs législateurs d'État en soutien au projet de loi A07954.</p>
    <p><strong>Campagnes d'inscription de donneurs :</strong> Nous nous associons à Donate Life pour organiser des événements d'inscription sur les campus universitaires.</p>

    <blockquote>« Avril nous offre une plateforme. Mais notre travail ne s'arrête pas à la fin du mois. Nous plaidons en faveur du consentement présumé pour le don d'organes 365 jours par an. » — Membre du YCOD</blockquote>

    <h3>Comment participer</h3>
    <p>Que ce soit avril ou non, vous pouvez faire la différence — et je le pense sincèrement. Inscrivez-vous comme donneur d'organes. Parlez à votre famille de vos souhaits. Écrivez à vos législateurs d'État pour soutenir le consentement présumé au don d'organes et le <a href="/bill" target="_blank">projet de loi A07954</a>. Partagez des informations sur le don d'organes sur les réseaux sociaux. Et si vous êtes étudiant, je vous veux dans notre équipe — envisagez de <a href="/join" target="_blank">rejoindre le YCOD</a>. Les jeunes ne sont pas apolitiques — ce sont des agents du changement. Soyez-en un.</p>
  `,

  'living-organ-donation-reaches-new-heights': `
    <p>Voici une nouvelle véritablement positive : le don d'organes de son vivant aux États-Unis a atteint un nouveau record en 2023, avec <strong>plus de 6 900 donneurs vivants</strong> — le chiffre le plus élevé de l'histoire du pays. Après qu'un membre de ma famille a eu besoin d'une greffe de rein, j'ai suivi ces chiffres de près. Les donneurs vivants, qui donnent le plus souvent un rein ou une partie de leur foie, représentent une part croissante de l'ensemble des greffes d'organes et offrent des avantages uniques par rapport au don post-mortem. C'est un progrès — mais ce n'est pas suffisant quand 17 personnes meurent encore chaque jour en attente.</p>

    <h3>Pourquoi le don de son vivant est important</h3>
    <p>Les organes provenant de donneurs vivants fonctionnent généralement mieux et durent plus longtemps que ceux de donneurs décédés. Un rein provenant d'un donneur vivant dure en moyenne 15 à 20 ans, contre 10 à 15 ans pour un donneur décédé. Le don de son vivant permet également une chirurgie programmée et élective — réduisant le chaos logistique du don post-mortem et aboutissant à de meilleurs résultats tant pour le donneur que pour le receveur. Et surtout, le don de son vivant augmente l'offre totale d'organes sans nécessiter le décès de quelqu'un.</p>

    <blockquote>« Chaque greffe de rein provenant d'un donneur vivant fait double emploi : elle sauve la vie du receveur et libère une place sur la liste d'attente des donneurs décédés pour quelqu'un d'autre. » — Fondation nationale du rein</blockquote>

    <h3>Le don croisé de reins</h3>
    <p>L'un des principaux moteurs de l'augmentation du don de son vivant est le <strong>don croisé de reins</strong> (KPD), également connu sous le nom d'échange de reins. Dans le cadre du KPD, des paires donneur-receveur incompatibles sont mises en correspondance avec d'autres paires pour créer des échanges compatibles. Des chaînes de dons croisés peuvent impliquer des dizaines de greffes déclenchées par un seul donneur altruiste. En 2023, les programmes de dons croisés ont facilité des centaines de greffes qui n'auraient pas été possibles par don direct seul.</p>

    <h3>Réduire les obstacles</h3>
    <p>La croissance du don de son vivant reflète également les efforts pour réduire les obstacles pour les donneurs. De nombreux États ont adopté des lois offrant aux donneurs vivants des protections de l'emploi, une couverture d'assurance et le remboursement de frais comme le transport et l'hébergement. Le Centre national d'aide aux donneurs vivants (National Living Donor Assistance Center), financé par la HRSA, fournit une aide financière aux donneurs qui ne peuvent pas assumer les coûts liés au don. Ces programmes ont rendu le don de son vivant accessible à une population plus large. Cela prouve ce que je ne cesse de répéter : quand on répare le système, pas les individus, de bonnes choses se produisent.</p>

    <blockquote>« Le plus grand obstacle au don de son vivant n'est pas la volonté — c'est le fardeau financier et logistique. Quand nous supprimons ces obstacles, davantage de personnes se manifestent. » — Société américaine des chirurgiens de transplantation</blockquote>

    <h3>Le YCOD soutient le don de son vivant</h3>
    <p>Bien que notre plaidoyer principal au YCOD se concentre sur la législation de consentement présumé pour le don post-mortem — en particulier le <a href="/bill" target="_blank">projet de loi A07954</a> — je défends personnellement aussi les efforts pour développer le don de son vivant. Les donneurs vivants sont des héros qui choisissent de subir une chirurgie majeure pour sauver la vie d'un inconnu. Nous mettons en lumière les témoignages de donneurs vivants dans nos campagnes et je m'assure que nos membres comprennent cette option. Il ne s'agit pas d'une seule voie pour sauver des vies — il s'agit de toutes les voies. Chaque greffe supplémentaire provenant d'un donneur vivant est une vie de plus sauvée, une famille de plus réunie. Changer le choix par défaut sauve des vies, et faciliter le don de son vivant aussi.</p>
  `,

  'george-lopez-kidney-transplant-advocacy': `
    <p>L'histoire de George Lopez est une histoire sur laquelle je reviens souvent parce qu'elle montre quelque chose que les gens ne voient pas dans la crise des organes : ce n'est pas seulement un problème médical — c'est un problème culturel et communautaire. En 2005, le comédien et acteur <strong>George Lopez</strong> a subi une greffe de rein après avoir été diagnostiqué d'une maladie rénale génétique. Son épouse d'alors, Ann Serrano Lopez, a donné l'un de ses reins pour lui sauver la vie. Depuis, Lopez utilise sa notoriété pour plaider en faveur du don d'organes, avec un accent particulier sur la sensibilisation dans la communauté latino — qui est touchée de manière disproportionnée par les maladies rénales. Sa voix compte parce que 17 personnes meurent chaque jour, et ces décès frappent certaines communautés plus durement que d'autres.</p>

    <h3>Le diagnostic</h3>
    <p>Lopez a été diagnostiqué d'une maladie rénale causée par un uretère étroit — une condition avec laquelle il avait vécu sans le savoir pendant des années. Au moment de la découverte, ses reins ne fonctionnaient plus qu'à moins de 20 % de leur capacité. La dialyse était une option, mais une greffe offrait la meilleure chance de mener une vie normale. Ann Lopez a été testée et s'est révélée compatible, et la greffe a été réalisée au centre médical Cedars-Sinai à Los Angeles.</p>

    <blockquote>« Ma femme m'a donné un rein. Elle m'a donné la vie. Je dois tout au don d'organes, et je passerai le reste de ma vie à m'assurer que d'autres personnes aient la même chance. » — George Lopez</blockquote>

    <h3>Plaidoyer pour la communauté latino</h3>
    <p>Lopez s'est montré particulièrement vocal sur le don d'organes dans la communauté latino, et je pense que son approche est exactement la bonne. Les Américains hispaniques sont 1,5 fois plus susceptibles de développer une insuffisance rénale que les Américains blancs non hispaniques, mais ils sont sous-représentés sur le registre des donneurs d'organes. Des facteurs culturels — notamment les préoccupations religieuses, la méfiance envers le système médical et les barrières linguistiques — contribuent à des taux de don plus faibles. C'est pourquoi je dis que c'est le système, pas les individus — quand le système ne va pas à la rencontre des communautés là où elles sont, les gens passent entre les mailles du filet. Lopez a travaillé à surmonter ces obstacles à travers des apparitions publiques, des interviews médiatiques et des partenariats avec Donate Life.</p>

    <h3>La fondation George Lopez</h3>
    <p>À travers sa fondation, Lopez a soutenu la recherche sur les maladies rénales, financé l'accès à la dialyse pour les communautés défavorisées et promu l'inscription au registre des donneurs d'organes. Il est apparu dans plusieurs campagnes Donate Life et parle régulièrement de son expérience de greffe dans des interviews et dans ses spectacles d'humour, touchant des audiences que les campagnes de santé traditionnelles atteignent rarement.</p>

    <blockquote>« Dans notre communauté, on ne parle pas de ces choses-là. Mais il le faut, parce que nos gens meurent à des taux plus élevés de maladies rénales. Je veux changer cette conversation. » — George Lopez</blockquote>

    <h3>La représentation compte</h3>
    <p>Nous, au YCOD, prenons cela à cœur : la représentation compte dans le plaidoyer pour le don d'organes. Quand quelqu'un comme George Lopez — une figure appréciée de la communauté latino — parle ouvertement de sa greffe, cela normalise la conversation et inspire l'action. Je travaille activement à ce que notre plaidoyer touche des communautés diverses, parce que la pénurie d'organes affecte tous les Américains, et la solution doit inclure tous les Américains aussi. Nos ressources multilingues et la diversité de nos membres reflètent cet engagement. La législation de consentement présumé comme le <a href="/bill" target="_blank">projet de loi A07954</a> aiderait chaque communauté — parce que changer le choix par défaut sauve des vies dans l'ensemble, en particulier dans les communautés actuellement mal desservies par le système de consentement explicite.</p>
  `,

  'youth-led-advocacy-changing-organ-donation': `
    <p>Je serai direct : quand j'ai fondé la <strong>Coalition des jeunes pour le don d'organes (YCOD)</strong>, beaucoup de gens trouvaient cela naïf — que des adolescents et de jeunes adultes puissent changer la politique de don d'organes aux États-Unis. J'ai entendu ce scepticisme. Je le comprenais. Mais je ne pouvais pas rester les bras croisés, pas après avoir appris que 17 personnes meurent chaque jour en attente d'organes, et pas après qu'un membre de ma famille a eu besoin d'une greffe de rein. Aujourd'hui, avec un réseau croissant d'étudiants militants à New York et au-delà, nous prouvons que le plaidoyer porté par les jeunes n'est pas seulement idéaliste — il est efficace.</p>

    <h3>Notre histoire fondatrice</h3>
    <p>Voici ce qui s'est passé : j'étais étudiant à New York quand j'ai été frappé par une statistique simple mais dévastatrice — 17 personnes meurent chaque jour aux États-Unis en attendant une greffe d'organe. Mais ce qui m'a vraiment marqué, c'est la prise de conscience que c'est un problème politique, pas médical. Les pays ayant un système de consentement présumé pour le don d'organes avaient des taux de don considérablement plus élevés. La question était évidente : pourquoi les États-Unis n'adoptent-ils pas le consentement présumé ? J'ai créé le YCOD pour trouver — et imposer — la réponse. Changer le choix par défaut sauve des vies, et j'étais déterminé à le prouver.</p>

    <blockquote>« Quand j'ai appris que 17 personnes meurent chaque jour en attente d'organes — et qu'un simple changement de politique pourrait prévenir nombre de ces décès — j'ai su que je ne pouvais pas rester les bras croisés. Le YCOD existe parce que les jeunes refusent d'accepter des morts évitables comme statu quo. » — Evan Roden, fondateur du YCOD</blockquote>

    <h3>Ce que nous faisons</h3>
    <p>Notre plaidoyer prend de nombreuses formes, et je suis fier de chacune d'entre elles :</p>
    <p><strong>Plaidoyer législatif :</strong> Nous plaidons en faveur du projet de loi A07954 de New York, qui établirait le consentement présumé pour le don d'organes dans l'État. Nos membres ont témoigné devant la Commission de la santé de l'Assemblée et organisé des campagnes de rédaction de lettres destinées à Albany.</p>
    <p><strong>Éducation :</strong> Nous menons des présentations dans les lycées et les universités de New York, éduquant les étudiants sur le don d'organes, la crise de la liste d'attente et le fonctionnement des systèmes de consentement présumé à travers le monde.</p>
    <p><strong>Engagement communautaire :</strong> Nous nous associons à Donate Life, à des organisations de santé et à d'autres associations pour organiser des campagnes d'inscription, des événements de sensibilisation et des collectes de fonds.</p>
    <p><strong>Plaidoyer numérique :</strong> Nous maintenons une présence active sur les réseaux sociaux, partageant des faits, des témoignages et des appels à l'action avec notre audience croissante de jeunes.</p>

    <h3>Pourquoi le plaidoyer des jeunes est important</h3>
    <p>J'en suis profondément convaincu : les jeunes ne sont pas apolitiques — ce sont des agents du changement. Nous apportons de l'énergie, une aisance numérique, une clarté morale et — peut-être le plus important — nous représentons l'avenir. Quand les législateurs voient des adolescents plaider avec passion pour la réforme du don d'organes, c'est plus difficile à ignorer. Les jeunes militants influencent également leurs familles : quand un étudiant rentre chez lui et parle de ce qu'il a appris sur le don d'organes, l'effet de propagation touche les parents, les grands-parents et des communautés entières. C'est ainsi qu'on construit un mouvement — pas de haut en bas, mais de la base vers le sommet.</p>

    <blockquote>« Les adultes ont créé ce système défaillant. Les jeunes vont le réparer. » — Membre du YCOD</blockquote>

    <h3>Rejoignez-nous</h3>
    <p>Le YCOD ne cesse de grandir, et je veux que vous en fassiez partie. Que vous soyez un étudiant souhaitant créer une section dans votre école, un membre de la communauté souhaitant faire du bénévolat, ou simplement quelqu'un qui croit que personne ne devrait mourir en attendant un organe — <a href="/join" target="_blank">rejoignez-nous</a>. Je ne pouvais pas rester les bras croisés, et je ne pense pas que vous devriez non plus. Ensemble, nous construisons un avenir où la liste d'attente de greffe d'organes appartient au passé — en commençant par le <a href="/bill" target="_blank">projet de loi A07954</a> et la législation de consentement présumé à New York. Changer le choix par défaut sauve des vies. Changeons-le.</p>
  `,
};
